# Generated by Django 3.2.6 on 2021-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210926_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
